---
name: test-actions
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          clivm_version: v1.14.0
          working_directory: tests
      - run: command -v clivm
      - run: clivm -v
      - run: github-comment -v
        working-directory: tests
  set-absolute-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          clivm_version: v1.14.0
          install_path: /tmp/bin/clivm
          working_directory: tests
      - run: /tmp/bin/clivm -v
  set-relative-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          clivm_version: v1.14.0
          install_path: bin/clivm
          working_directory: tests
      - run: tests/bin/clivm -v
